### ISSUE TITLE
Any possible performance regression?

### ISSUE THREAD

**Issue by theidexisted** [DarkMatterCore/libusbhsfs#18]
**Describe the bug**
We faced performance degression in https://github.com/XorTroll/Goldleaf/issues/590, it uses this project as a submodule, so I think we may have the root cause here.

**To Reproduce**

Compare old version of GoldLeaf and latest version and install some nsp files.

**Please fill the following information:**
- Horizon OS (Switch FW) version: [e.g. 10.0.0]  12.1.0
- CFW: [e.g. Atmosphère, SX OS, etc.] Atmosphère
- CFW version: [e.g. 0.11.1, 2.9.4, etc.]  0.19.5
- Atmosphère launch method (if applicable): [e.g. Hekate, fusee-primary] Hekate
- libusbhsfs version: [e.g. 0.0.2] https://github.com/DarkMatterCore/libusbhsfs/tree/782aa51e0aa149427664cc3a9c2e520937576fcc
- Homebrew launch method: [e.g. title override, applet] 
- USB Mass Storage device specs: [e.g. WD My Passport 1 TB, exFAT partition] exFAT MicroSD/Samsung 128 GB PRO Endurance

**Logfile**
Make sure you're using an application that's linked against the debug version of the library, and upload your logfile located at `sdmc:/libusbhsfs.log`.

**Additional context**

**Comment by DarkMatterCore** [comment]
@theidexisted  Other installers use multithreading to speed up the installation process. Goldleaf is, to my knowledge, single threaded, which means UI updating + NSP reading + content installation is all carried out under a single thread - this may severely decrease the performance.

Furthermore, the Goldleaf build being used by @EXO5KELETON must not have been linked against the debug version of libusbhsfs - this version constantly logs data to the SD card, and yes, may severely impact the performance as well (it's an expected tradeout).

Finally, it'd be good to know the other installers used by @EXO5KELETON. All open source installers compatible with USB Mass Storage devices use libusbhsfs - if better performance was displayed by one of these, then the problem lies within Goldleaf.

**Comment by theidexisted** [comment]
Thanks so much for the quick and detailed response, I have switched to AWOO and get 2 times faster.
